# Generated by Django 2.2.9 on 2021-05-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_attendance_end_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='end_img',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_img',
        ),
    ]
