# Generated by Django 2.2.9 on 2021-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_auto_20210529_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='end_gps',
            new_name='end_latitude',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='start_gps',
            new_name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
